"""add system_settings table

Revision ID: 598e64967db0
Revises: 924572ca27d8
Create Date: 2026-02-14 10:40:20.897101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598e64967db0'
down_revision = '924572ca27d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint('system_settings_key_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.create_unique_constraint('system_settings_key_key', ['key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
