"""Add user_id

Revision ID: 924572ca27d8
Revises: 764b1768bdbd
Create Date: 2026-01-24 23:26:37.088042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924572ca27d8'
down_revision = '764b1768bdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('ix_courses_id')

    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_embeddings_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_embeddings_user_id'))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_id', ['id'], unique=False)

    # ### end Alembic commands ###
